# Copyright 2025 Bosutech XXI S.L.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
from enum import Enum
from typing import Literal

from pydantic import BaseModel, Field, model_validator
from typing_extensions import Self

from nucliadb_models.filters import FilterExpression
from nucliadb_models.graph.requests import GraphPathQuery
from nucliadb_models.search import (
    Image,
    RankFusion,
    RankFusionName,
    Reranker,
    RerankerName,
    SearchParamDefaults,
)
from nucliadb_models.security import RequestSecurity


class KeywordQuery(BaseModel, extra="forbid"):
    query: str
    min_score: float = 0.0
    with_synonyms: bool = False


class SemanticQuery(BaseModel, extra="forbid"):
    query: list[float]
    vectorset: str
    min_score: float = -1.0


class GraphQuery(BaseModel, extra="forbid"):
    query: GraphPathQuery


class RawQuery(BaseModel, extra="forbid"):
    """Low-level query with per-index options."""

    keyword: KeywordQuery | None = None
    semantic: SemanticQuery | None = None
    graph: GraphQuery | None = None


class Rephrase(BaseModel, extra="forbid"):
    prompt: str = Field(
        description=(
            "Rephrase prompt given to the generative model responsible for rephrasing the query for a more effective retrieval step.\n"
            "If not specified, Nuclia's default prompt is used. It must include the {question} placeholder. "
            "The placeholder will be replaced with the original question"
        ),
        min_length=1,
        examples=[
            """\
Rephrase this question so its better for retrieval, and keep the rephrased question in the same language as the original.
QUESTION: {question}
Please return ONLY the question without any explanation. Just the rephrased question.""",
            """\
Rephrase this question so its better for retrieval, identify any part numbers and append them to the end of the question separated by a commas.
QUESTION: {question}
Please return ONLY the question without any explanation.""",
        ],
    )


class KeywordOverrides(BaseModel, extra="forbid"):
    min_score: float | None = None
    with_synonyms: bool = False


class SemanticOverrides(BaseModel, extra="forbid"):
    vector: list[float] | None = None
    vectorset: str | None = None
    min_score: float | None = None


class GraphOverrides(BaseModel, extra="forbid"):
    query: GraphPathQuery | None = None


class QueryOverrides(BaseModel, extra="forbid"):
    keyword: KeywordOverrides | Literal["disabled"] | None = Field(
        default=None,
        description="Override keyword search parameters. Using false disables keyword search",
    )
    semantic: SemanticOverrides | Literal["disabled"] | None = Field(
        default=None,
        description="Override semantic search parameters. Using false disables semantic search",
    )
    graph: GraphOverrides | Literal["disabled"] | None = Field(
        default=None,
        description="Override graph search parameters. Using false disables graph search",
    )

    @model_validator(mode="after")
    def cant_disable_all(self) -> Self:
        if self.keyword == self.semantic == self.graph == "disabled":
            raise ValueError("disabling all searches is not allowed as it'd never return any result")

        return self


class Query(BaseModel, extra="forbid"):
    """A high-level query to retrieve what you want with overridable low-level details."""

    query: str = Field(description="Textual query to search for")
    rephrase: bool | Rephrase = Field(
        default=False,
        description="Rephrase query in order to improve retrieval. This is an expensive operation involving LLMs",
    )
    image: Image | None = Field(
        default=None,
        description="Image that will be used together with the query text for retrieval",
    )
    override: QueryOverrides = Field(
        default_factory=QueryOverrides,
        description="Override advanced retrieval behavior generated by other options or defaults",
    )


class Filters(BaseModel, extra="forbid"):
    filter_expression: FilterExpression | None = (
        SearchParamDefaults.filter_expression.to_pydantic_field()
    )
    show_hidden: bool = SearchParamDefaults.show_hidden.to_pydantic_field()
    security: RequestSecurity | None = SearchParamDefaults.security.to_pydantic_field()
    with_duplicates: bool = False


class RetrievalRequest(BaseModel, extra="forbid"):
    query: Query | RawQuery
    top_k: int = Field(default=20, gt=0, le=500)
    filters: Filters = Field(default_factory=Filters)
    rank_fusion: RankFusionName | RankFusion = Field(default=RankFusionName.RECIPROCAL_RANK_FUSION)
    reranker: RerankerName | Reranker | None = Field(
        default=None,
        description="Rerank results using a reranker. Depending on the reranker this may be a costly operation",
    )


class ScoreSource(str, Enum):
    INDEX = "index"
    RANK_FUSION = "rank_fusion"
    RERANKER = "reranker"


class ScoreType(str, Enum):
    SEMANTIC = "semantic"
    KEYWORD = "keyword"
    GRAPH = "graph"
    RRF = "rrf"
    WCOMB_SUM = "wCombSUM"
    RERANKER = "reranker"


class KeywordScore(BaseModel, extra="forbid"):
    score: float
    source: Literal[ScoreSource.INDEX] = ScoreSource.INDEX
    type: Literal[ScoreType.KEYWORD] = ScoreType.KEYWORD


class SemanticScore(BaseModel, extra="forbid"):
    score: float
    source: Literal[ScoreSource.INDEX] = ScoreSource.INDEX
    type: Literal[ScoreType.SEMANTIC] = ScoreType.SEMANTIC


class GraphScore(BaseModel, extra="forbid"):
    score: float
    source: Literal[ScoreSource.INDEX] = ScoreSource.INDEX
    type: Literal[ScoreType.GRAPH] = ScoreType.GRAPH


class RrfScore(BaseModel, extra="forbid"):
    score: float
    source: Literal[ScoreSource.RANK_FUSION] = ScoreSource.RANK_FUSION
    type: Literal[ScoreType.RRF] = ScoreType.RRF


class WeightedCombSumScore(BaseModel, extra="forbid"):
    score: float
    source: Literal[ScoreSource.RANK_FUSION] = ScoreSource.RANK_FUSION
    type: Literal[ScoreType.WCOMB_SUM] = ScoreType.WCOMB_SUM


class RerankerScore(BaseModel, extra="forbid"):
    score: float
    source: Literal[ScoreSource.RERANKER] = ScoreSource.RERANKER
    type: Literal[ScoreType.RERANKER] = ScoreType.RERANKER


Score = KeywordScore | SemanticScore | GraphScore | RrfScore | WeightedCombSumScore | RerankerScore


class Scores(BaseModel, extra="forbid"):
    value: float
    source: ScoreSource
    type: ScoreType
    history: list[Score]


class Metadata(BaseModel, extra="forbid"):
    field_labels: list[str]
    paragraph_labels: list[str]

    is_an_image: bool
    is_a_table: bool

    # for extracted from visual content (ocr, inception, tables)
    source_file: str | None

    # for documents (pdf, docx...) only
    page: int | None
    in_page_with_visual: bool | None


class RetrievalMatch(BaseModel, extra="forbid"):
    id: str
    score: Scores
    metadata: Metadata


class RetrievalResponse(BaseModel, extra="forbid"):
    matches: list[RetrievalMatch]
