# Copyright (C) 2021 Bosutech XXI S.L.
#
# nucliadb is offered under the AGPL v3.0 and as commercial software.
# For commercial licensing, contact us at info@nuclia.com.
#
# AGPL:
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#


from pydantic import BaseModel


class VectorSetHNSWIndex(BaseModel):
    # Id of the node containing the hnsw index
    node_id: str
    # Id of the shard containing the hnsw index
    shard_replica_id: str
    # This is the ID generated by the nucliadb node on vectorset creation
    hnsw_index_id: str


class VectorSet(BaseModel):
    id: str
    indexes: list[VectorSetHNSWIndex]
    semantic_model: str
    semantic_vector_similarity: str
    semantic_vector_size: int
    semantic_threshold: float
    semantic_matryoshka_dimensions: list[int]


class VectorSets(BaseModel):
    vectorsets: dict[str, VectorSet]
