import abc
from abc import ABC
from pkg_resources import EntryPoint

class BaseDistro(ABC, metaclass=abc.ABCMeta):
    def __new__(cls, *args, **kwargs): ...
    def configure(self, **kwargs) -> None: ...
    def load_instrumentor(self, entry_point: EntryPoint, **kwargs): ...

class DefaultDistro(BaseDistro): ...
