from opentelemetry.trace import StatusCode
from typing import Dict, Sequence

def extract_attributes_from_object(obj: any, attributes: Sequence[str], existing: Dict[str, str] = ...) -> Dict[str, str]: ...
def http_status_to_status_code(status: int, allow_redirect: bool = ..., server_span: bool = ...) -> StatusCode: ...
def unwrap(obj, attr: str): ...
