protos:
	cd ../../../ && python -m grpc_tools.protoc nucliadb_telemetry/tests/grpc/helloworld.proto        -I . --python_out=. --mypy_out=. --grpc_python_out=. --mypy_grpc_out=.
	cd ../../../ && python -m grpc_tools.protoc nucliadb_telemetry/tests/grpc/hellostreamingworld.proto        -I . --python_out=. --mypy_out=. --grpc_python_out=. --mypy_grpc_out=.
