apiVersion: v1
kind: ConfigMap
metadata:
  name: train-config
  labels:
    app: train
    app.kubernetes.io/name: train
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    version: "{{ .Chart.Version | replace "+" "_" }}"
    chart: "{{ .Chart.Name }}"
data:
  GRPC_PORT: {{ .Values.serving.grpc_port | quote }}
  SERVING_PORT: {{ .Values.serving.port | quote }}
{{- if .Values.tracing.enabled }}
  {{- if .Values.tracing.otlp_collector_endpoint }}
  OTLP_COLLECTOR_ENDPOINT: {{ .Values.tracing.otlp_collector_endpoint | quote }}
  {{- else }}
  JAEGER_ENABLED: "true"
  {{- end }}
{{- end }}
  METRICS_PORT: {{ .Values.serving.metricsPort | quote }}

