from collections.abc import MutableMapping
from opentelemetry.util import types as types
from typing import Any, Optional

class BoundedAttributes(MutableMapping):
    maxlen: Any
    dropped: int
    max_value_len: Any
    def __init__(self, maxlen: Optional[int] = ..., attributes: types.Attributes = ..., immutable: bool = ..., max_value_len: Optional[int] = ...) -> None: ...
    def __getitem__(self, key): ...
    def __setitem__(self, key, value) -> None: ...
    def __delitem__(self, key) -> None: ...
    def __iter__(self): ...
    def __len__(self): ...
    def copy(self): ...
