from opentelemetry.context.context import Context as Context
from typing import Mapping, Optional

def get_all(context: Optional[Context] = ...) -> Mapping[str, object]: ...
def get_baggage(name: str, context: Optional[Context] = ...) -> Optional[object]: ...
def set_baggage(name: str, value: object, context: Optional[Context] = ...) -> Context: ...
def remove_baggage(name: str, context: Optional[Context] = ...) -> Context: ...
def clear(context: Optional[Context] = ...) -> Context: ...
