protos:
	python -m grpc_tools.protoc helloworld.proto        -I ./../../../ --python_out=./ --mypy_out=./ --grpc_python_out=./ --mypy_grpc_out=./
	python -m grpc_tools.protoc hellostreamingworld.proto        -I ./../../../ --python_out=./ --mypy_out=./ --grpc_python_out=./ --mypy_grpc_out=./