PUB_OP: str
HPUB_OP: str
SUB_OP: str
UNSUB_OP: str

def pub_cmd(subject, reply, payload): ...
def hpub_cmd(subject, reply, hdr, payload): ...
def sub_cmd(subject, queue, sid): ...
def unsub_cmd(sid, limit): ...
