
export:
	nucliadb_export --dump=$(slug).export --host=ingest.nucliadb.svc.cluster.local --http=8080 --grpc=8030 --slug=$(slug) --reader_host=reader.nucliadb.svc.cluster.local --writer_host=writer.nucliadb.svc.cluster.local --grpc_host=ingest.nucliadb.svc.cluster.local