from enum import Enum

class SpanAttributes:
    AWS_LAMBDA_INVOKED_ARN: str
    DB_SYSTEM: str
    DB_CONNECTION_STRING: str
    DB_USER: str
    DB_JDBC_DRIVER_CLASSNAME: str
    DB_NAME: str
    DB_STATEMENT: str
    DB_OPERATION: str
    NET_PEER_NAME: str
    NET_PEER_IP: str
    NET_PEER_PORT: str
    NET_TRANSPORT: str
    DB_MSSQL_INSTANCE_NAME: str
    DB_CASSANDRA_KEYSPACE: str
    DB_CASSANDRA_PAGE_SIZE: str
    DB_CASSANDRA_CONSISTENCY_LEVEL: str
    DB_CASSANDRA_TABLE: str
    DB_CASSANDRA_IDEMPOTENCE: str
    DB_CASSANDRA_SPECULATIVE_EXECUTION_COUNT: str
    DB_CASSANDRA_COORDINATOR_ID: str
    DB_CASSANDRA_COORDINATOR_DC: str
    DB_HBASE_NAMESPACE: str
    DB_REDIS_DATABASE_INDEX: str
    DB_MONGODB_COLLECTION: str
    DB_SQL_TABLE: str
    EXCEPTION_TYPE: str
    EXCEPTION_MESSAGE: str
    EXCEPTION_STACKTRACE: str
    EXCEPTION_ESCAPED: str
    FAAS_TRIGGER: str
    FAAS_EXECUTION: str
    FAAS_DOCUMENT_COLLECTION: str
    FAAS_DOCUMENT_OPERATION: str
    FAAS_DOCUMENT_TIME: str
    FAAS_DOCUMENT_NAME: str
    HTTP_METHOD: str
    HTTP_URL: str
    HTTP_TARGET: str
    HTTP_HOST: str
    HTTP_SCHEME: str
    HTTP_STATUS_CODE: str
    HTTP_FLAVOR: str
    HTTP_USER_AGENT: str
    HTTP_REQUEST_CONTENT_LENGTH: str
    HTTP_REQUEST_CONTENT_LENGTH_UNCOMPRESSED: str
    HTTP_RESPONSE_CONTENT_LENGTH: str
    HTTP_RESPONSE_CONTENT_LENGTH_UNCOMPRESSED: str
    HTTP_SERVER_NAME: str
    HTTP_ROUTE: str
    HTTP_CLIENT_IP: str
    NET_HOST_IP: str
    NET_HOST_PORT: str
    NET_HOST_NAME: str
    NET_HOST_CONNECTION_TYPE: str
    NET_HOST_CONNECTION_SUBTYPE: str
    NET_HOST_CARRIER_NAME: str
    NET_HOST_CARRIER_MCC: str
    NET_HOST_CARRIER_MNC: str
    NET_HOST_CARRIER_ICC: str
    MESSAGING_SYSTEM: str
    MESSAGING_DESTINATION: str
    MESSAGING_DESTINATION_KIND: str
    MESSAGING_TEMP_DESTINATION: str
    MESSAGING_PROTOCOL: str
    MESSAGING_PROTOCOL_VERSION: str
    MESSAGING_URL: str
    MESSAGING_MESSAGE_ID: str
    MESSAGING_CONVERSATION_ID: str
    MESSAGING_MESSAGE_PAYLOAD_SIZE_BYTES: str
    MESSAGING_MESSAGE_PAYLOAD_COMPRESSED_SIZE_BYTES: str
    FAAS_TIME: str
    FAAS_CRON: str
    FAAS_COLDSTART: str
    FAAS_INVOKED_NAME: str
    FAAS_INVOKED_PROVIDER: str
    FAAS_INVOKED_REGION: str
    PEER_SERVICE: str
    ENDUSER_ID: str
    ENDUSER_ROLE: str
    ENDUSER_SCOPE: str
    THREAD_ID: str
    THREAD_NAME: str
    CODE_FUNCTION: str
    CODE_NAMESPACE: str
    CODE_FILEPATH: str
    CODE_LINENO: str
    RPC_SYSTEM: str
    RPC_SERVICE: str
    RPC_METHOD: str
    AWS_DYNAMODB_TABLE_NAMES: str
    AWS_DYNAMODB_CONSUMED_CAPACITY: str
    AWS_DYNAMODB_ITEM_COLLECTION_METRICS: str
    AWS_DYNAMODB_PROVISIONED_READ_CAPACITY: str
    AWS_DYNAMODB_PROVISIONED_WRITE_CAPACITY: str
    AWS_DYNAMODB_CONSISTENT_READ: str
    AWS_DYNAMODB_PROJECTION: str
    AWS_DYNAMODB_LIMIT: str
    AWS_DYNAMODB_ATTRIBUTES_TO_GET: str
    AWS_DYNAMODB_INDEX_NAME: str
    AWS_DYNAMODB_SELECT: str
    AWS_DYNAMODB_GLOBAL_SECONDARY_INDEXES: str
    AWS_DYNAMODB_LOCAL_SECONDARY_INDEXES: str
    AWS_DYNAMODB_EXCLUSIVE_START_TABLE: str
    AWS_DYNAMODB_TABLE_COUNT: str
    AWS_DYNAMODB_SCAN_FORWARD: str
    AWS_DYNAMODB_SEGMENT: str
    AWS_DYNAMODB_TOTAL_SEGMENTS: str
    AWS_DYNAMODB_COUNT: str
    AWS_DYNAMODB_SCANNED_COUNT: str
    AWS_DYNAMODB_ATTRIBUTE_DEFINITIONS: str
    AWS_DYNAMODB_GLOBAL_SECONDARY_INDEX_UPDATES: str
    MESSAGING_OPERATION: str
    MESSAGING_RABBITMQ_ROUTING_KEY: str
    MESSAGING_KAFKA_MESSAGE_KEY: str
    MESSAGING_KAFKA_CONSUMER_GROUP: str
    MESSAGING_KAFKA_CLIENT_ID: str
    MESSAGING_KAFKA_PARTITION: str
    MESSAGING_KAFKA_TOMBSTONE: str
    RPC_GRPC_STATUS_CODE: str
    RPC_JSONRPC_VERSION: str
    RPC_JSONRPC_REQUEST_ID: str
    RPC_JSONRPC_ERROR_CODE: str
    RPC_JSONRPC_ERROR_MESSAGE: str

class DbSystemValues(Enum):
    OTHER_SQL: str
    MSSQL: str
    MYSQL: str
    ORACLE: str
    DB2: str
    POSTGRESQL: str
    REDSHIFT: str
    HIVE: str
    CLOUDSCAPE: str
    HSQLDB: str
    PROGRESS: str
    MAXDB: str
    HANADB: str
    INGRES: str
    FIRSTSQL: str
    EDB: str
    CACHE: str
    ADABAS: str
    FIREBIRD: str
    DERBY: str
    FILEMAKER: str
    INFORMIX: str
    INSTANTDB: str
    INTERBASE: str
    MARIADB: str
    NETEZZA: str
    PERVASIVE: str
    POINTBASE: str
    SQLITE: str
    SYBASE: str
    TERADATA: str
    VERTICA: str
    H2: str
    COLDFUSION: str
    CASSANDRA: str
    HBASE: str
    MONGODB: str
    REDIS: str
    COUCHBASE: str
    COUCHDB: str
    COSMOSDB: str
    DYNAMODB: str
    NEO4J: str
    GEODE: str
    ELASTICSEARCH: str
    MEMCACHED: str
    COCKROACHDB: str

class NetTransportValues(Enum):
    IP_TCP: str
    IP_UDP: str
    IP: str
    UNIX: str
    PIPE: str
    INPROC: str
    OTHER: str

class DbCassandraConsistencyLevelValues(Enum):
    ALL: str
    EACH_QUORUM: str
    QUORUM: str
    LOCAL_QUORUM: str
    ONE: str
    TWO: str
    THREE: str
    LOCAL_ONE: str
    ANY: str
    SERIAL: str
    LOCAL_SERIAL: str

class FaasTriggerValues(Enum):
    DATASOURCE: str
    HTTP: str
    PUBSUB: str
    TIMER: str
    OTHER: str

class FaasDocumentOperationValues(Enum):
    INSERT: str
    EDIT: str
    DELETE: str

class HttpFlavorValues(Enum):
    HTTP_1_0: str
    HTTP_1_1: str
    HTTP_2_0: str
    SPDY: str
    QUIC: str

class NetHostConnectionTypeValues(Enum):
    WIFI: str
    WIRED: str
    CELL: str
    UNAVAILABLE: str
    UNKNOWN: str

class NetHostConnectionSubtypeValues(Enum):
    GPRS: str
    EDGE: str
    UMTS: str
    CDMA: str
    EVDO_0: str
    EVDO_A: str
    CDMA2000_1XRTT: str
    HSDPA: str
    HSUPA: str
    HSPA: str
    IDEN: str
    EVDO_B: str
    LTE: str
    EHRPD: str
    HSPAP: str
    GSM: str
    TD_SCDMA: str
    IWLAN: str
    NR: str
    NRNSA: str
    LTE_CA: str

class MessagingDestinationKindValues(Enum):
    QUEUE: str
    TOPIC: str

class FaasInvokedProviderValues(Enum):
    ALIBABA_CLOUD: str
    AWS: str
    AZURE: str
    GCP: str

class MessagingOperationValues(Enum):
    RECEIVE: str
    PROCESS: str

class RpcGrpcStatusCodeValues(Enum):
    OK: int
    CANCELLED: int
    UNKNOWN: int
    INVALID_ARGUMENT: int
    DEADLINE_EXCEEDED: int
    NOT_FOUND: int
    ALREADY_EXISTS: int
    PERMISSION_DENIED: int
    RESOURCE_EXHAUSTED: int
    FAILED_PRECONDITION: int
    ABORTED: int
    OUT_OF_RANGE: int
    UNIMPLEMENTED: int
    INTERNAL: int
    UNAVAILABLE: int
    DATA_LOSS: int
    UNAUTHENTICATED: int
