import nats.errors

class NatsError(nats.errors.Error): ...
class ErrConnectionClosed(nats.errors.ConnectionClosedError): ...
class ErrDrainTimeout(nats.errors.DrainTimeoutError): ...
class ErrInvalidUserCredentials(nats.errors.InvalidUserCredentialsError): ...
class ErrInvalidCallbackType(nats.errors.InvalidCallbackTypeError): ...
class ErrConnectionReconnecting(nats.errors.ConnectionReconnectingError): ...
class ErrConnectionDraining(nats.errors.ConnectionDrainingError): ...
class ErrMaxPayload(nats.errors.MaxPayloadError): ...
class ErrStaleConnection(nats.errors.StaleConnectionError): ...
class ErrJsonParse(nats.errors.JsonParseError): ...
class ErrSecureConnRequired(nats.errors.SecureConnRequiredError): ...
class ErrSecureConnWanted(nats.errors.SecureConnWantedError): ...
class ErrSecureConnFailed(nats.errors.SecureConnFailedError): ...
class ErrBadSubscription(nats.errors.BadSubscriptionError): ...
class ErrBadSubject(nats.errors.BadSubjectError): ...
class ErrSlowConsumer(nats.errors.SlowConsumerError): ...
class ErrTimeout(nats.errors.TimeoutError): ...
class ErrBadTimeout(nats.errors.BadTimeoutError): ...
class ErrAuthorization(nats.errors.AuthorizationError): ...
class ErrNoServers(nats.errors.NoServersError): ...
