import typing
from opentelemetry.context.context import Context
from typing import Any

logger: Any

def create_key(keyname: str) -> str: ...
def get_value(key: str, context: typing.Optional[Context] = ...) -> object: ...
def set_value(key: str, value: object, context: typing.Optional[Context] = ...) -> Context: ...
def get_current() -> Context: ...
def attach(context: Context) -> object: ...
def detach(token: object) -> None: ...
