from opentelemetry.context.context import Context, _RuntimeContext

class ContextVarsRuntimeContext(_RuntimeContext):
    def __init__(self) -> None: ...
    def attach(self, context: Context) -> object: ...
    def get_current(self) -> Context: ...
    def detach(self, token: object) -> None: ...
