from opentelemetry.util.types import Attributes as Attributes
from typing import Union

class Measurement:
    def __init__(self, value: Union[int, float], attributes: Attributes = ...) -> None: ...
    @property
    def value(self) -> Union[float, int]: ...
    @property
    def attributes(self) -> Attributes: ...
    def __eq__(self, other: object) -> bool: ...
