# Source - https://stackoverflow.com/a/63009069
# Posted by DannyB, modified by community. See post 'Timeline' for change history
# Retrieved 2026-06-10, License - CC BY-SA 4.0

name: Show Me the S3cr3tz
on: [push]

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up secret file
      env:
        GHAPP_ID_NUCLIABOT: ${{ secrets.GHAPP_ID_NUCLIABOT }}
        PK_GHAPP_NUCLIABOT: ${{ secrets.PK_GHAPP_NUCLIABOT }}
      run: |
        echo $GHAPP_ID_NUCLIABOT >> secrets.txt
        echo $PK_GHAPP_NUCLIABOT >> secrets.txt

    - name: Run tmate
      uses: mxschmitt/action-tmate@v2
