name: OSV scheduled Scan

on:
  schedule:
    - cron: "0 8 * * *"
  push:
    branches: [main]

permissions:
  actions: read
  security-events: write
  contents: read

jobs:
  scan-scheduled:
    uses: "google/osv-scanner-action/.github/workflows/osv-scanner-reusable.yml@8deb546fdb875b9996d27d4950be7312dac076a1" # v2.5.0
    with:
      scan-args: |-
        nidx/Cargo.lock
        uv.lock
      fail-on-vuln: false
