name: Trufflehog - Secrets security scan
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  trufflehog-scan:
    runs-on: nuclia-base
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
      
      - name: TruffleHog
        uses: trufflesecurity/trufflehog@20652fbbdefffcdaa493a5bf57ab2ac6b1db715b # v3.97.1
        with:
          extra_args: --results=verified,unknown