name: Trufflehog - Secrets security scan
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  trufflehog-scan:
    runs-on: nuclia-base
    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0
      
      - name: TruffleHog
        uses: trufflesecurity/trufflehog@30d5bb91af1a771378349dbbb0c82129392acf70 # v3.95.6
        with:
          extra_args: --results=verified,unknown